version: 2

sources:
  - name: raw
    database: FINANCE_WAREHOUSE
    schema: RAW
    description: "Raw data from ETL pipeline"
    tables:
      - name: STG_COMPANIES
        description: "Source table for company dimension data"
        
      - name: STG_STOCK_PRICES
        description: "Source table for daily stock prices"

models:
  - name: stg_companies
    description: "Cleaned company dimension"
    columns:
      - name: company_id
        description: "Surrogate key for company"
        tests:
          - unique
          - not_null
      - name: ticker
        description: "Stock ticker symbol"
        tests:
          - unique
          - not_null

  - name: stg_stock_prices
    description: "Cleaned stock price data with calculated metrics"
    columns:
      - name: ticker
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: price_date
        description: "Date of price"
        tests:
          - not_null

  - name: fact_daily_prices
    description: "Fact table for daily stock prices"
    columns:
      - name: company_id
        description: "Foreign key to company dimension"
        tests:
          - not_null
      - name: close_price
        description: "Closing price"
        tests:
          - not_null